/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication7;

import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Alysa Emilio
 */
public class JavaVotingApp extends javax.swing.JFrame {

    /**
     * Creates new form JavaVotingApp
     */
    public JavaVotingApp() {
        initComponents();
        this.setSize(990, 509);
        setLocationRelativeTo(null);
        this.setTitle("VOTING APP");
        jTextField1.setVisible(true);
        jTextField2.setVisible(true);
        
        
    }
        int codmvote;
        int pubgmvote;
        int vote = 1;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        codmbtn = new javax.swing.JToggleButton();
        pubgmbtn = new javax.swing.JToggleButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jToggleButton1 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication7/codmF.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(120, 130, 300, 169);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication7/pubgmF.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(540, 130, 300, 170);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("WHAT GAME IS MORE POPULAR?");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(200, 30, 570, 48);

        jButton3.setBackground(new java.awt.Color(0, 0, 204));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("RESULTS");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(720, 450, 100, 23);

        jButton4.setBackground(new java.awt.Color(0, 0, 204));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("BACK");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(850, 450, 100, 23);

        codmbtn.setBackground(new java.awt.Color(204, 0, 0));
        codmbtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        codmbtn.setForeground(new java.awt.Color(0, 0, 0));
        codmbtn.setText("VOTE");
        codmbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codmbtnActionPerformed(evt);
            }
        });
        jPanel1.add(codmbtn);
        codmbtn.setBounds(220, 320, 111, 23);

        pubgmbtn.setBackground(new java.awt.Color(204, 0, 51));
        pubgmbtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        pubgmbtn.setForeground(new java.awt.Color(0, 0, 0));
        pubgmbtn.setText("VOTE");
        pubgmbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pubgmbtnActionPerformed(evt);
            }
        });
        jPanel1.add(pubgmbtn);
        pubgmbtn.setBounds(640, 320, 111, 23);

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(0, 0, 0));
        jTextField1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(0, 153, 0));
        jTextField1.setText("0");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(220, 360, 110, 26);

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(0, 0, 0));
        jTextField2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(0, 204, 51));
        jTextField2.setText("0");
        jPanel1.add(jTextField2);
        jTextField2.setBounds(640, 360, 110, 26);

        jToggleButton1.setText("DONE");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton1);
        jToggleButton1.setBounds(440, 380, 100, 23);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 990, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 509, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        JavaVotingAppLoginWindow n = new JavaVotingAppLoginWindow();
        n.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(Integer.toString(codmvote));
        jTextField2.setText(Integer.toString(pubgmvote));
        
        
        JavaVotingAppResults x = new JavaVotingAppResults();
        JavaVotingAppResults.jTextField1.setText(JavaVotingApp.jTextField1.getText());
        JavaVotingAppResults.jTextField2.setText(JavaVotingApp.jTextField2.getText());
        x.setVisible(true);
        
//        this.setVisible(false);
        dispose();
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void codmbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codmbtnActionPerformed
        // TODO add your handling code here:
        if (vote==1) {
            if (codmvote >= 0){
                codmvote++;
                vote --;
            }            
        }
        else {
        codmvote = (Integer.parseInt(jTextField1.getText()))+1;
        JOptionPane.showMessageDialog(null, "You voted Call of Duty");
        jTextField1.setText(Integer.toString(codmvote));
        }    
        
    }//GEN-LAST:event_codmbtnActionPerformed

    private void pubgmbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pubgmbtnActionPerformed
        // TODO add your handling code here:
        if (vote==1) {
            if (codmvote >= 0){
                codmvote++;
                vote --;
            }            
        }
        else {
        pubgmvote = (Integer.parseInt(jTextField2.getText()))+1;
        javax.swing.JOptionPane.showMessageDialog(null, "You voted Pubg Mobile");
        jTextField2.setText(Integer.toString(pubgmvote));
       
        }
        
    }//GEN-LAST:event_pubgmbtnActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        JavaVotingAppLoginWindow n = new JavaVotingAppLoginWindow();
        n.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JavaVotingApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JavaVotingApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JavaVotingApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JavaVotingApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JavaVotingApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton codmbtn;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JTextField jTextField1;
    public static javax.swing.JTextField jTextField2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton pubgmbtn;
    // End of variables declaration//GEN-END:variables
}
